# -*- coding: utf-8 -*-
"""GNN_PROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zpVdkZ0KYF2Ckm3pWYPBHrdXID9bX0S6
"""

!pip install torch-geometric

import kagglehub
import pandas as pd
import numpy as np

import torch
import torch.nn as nn
import torch.nn.functional as F

from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report
)

from torch_geometric.data import Data
from torch_geometric.nn import (
    GCNConv,
    SAGEConv,
    GATConv
)

# =====================================================
# DOWNLOAD AND LOAD DATASET
# =====================================================

path = kagglehub.dataset_download(
    "ellipticco/elliptic-data-set"
)

print("Dataset Path:", path)

DATA_DIR = f"{path}/elliptic_bitcoin_dataset"

feat_cols = (
    ["txId", "time_step"] +
    [f"f{i}" for i in range(1, 166)]
)

df_features = pd.read_csv(
    f"{DATA_DIR}/elliptic_txs_features.csv",
    header=None,
    names=feat_cols
)

df_edges = pd.read_csv(
    f"{DATA_DIR}/elliptic_txs_edgelist.csv"
)

df_classes = pd.read_csv(
    f"{DATA_DIR}/elliptic_txs_classes.csv"
)

print(df_features.shape)
print(df_edges.shape)
print(df_classes.shape)

# =====================================================
# LABEL PROCESSING
# =====================================================

label_map = {
    "1": 1,
    "2": 0,
    "unknown": -1
}

df = df_features.merge(
    df_classes,
    on="txId"
)

df["label"] = (
    df["class"]
    .astype(str)
    .map(label_map)
)

# =====================================================
# FEATURES
# =====================================================

feature_cols = [f"f{i}" for i in range(1,166)]

X = df[feature_cols].values.astype(np.float32)

scaler = StandardScaler()

X = scaler.fit_transform(X)

x = torch.tensor(
    X,
    dtype=torch.float
)

# =====================================================
# LABELS
# =====================================================

y = torch.tensor(
    df["label"].values,
    dtype=torch.long
)

# =====================================================
# NODE MAPPING
# =====================================================

node_map = {
    txid:i
    for i,txid in enumerate(df["txId"])
}

# =====================================================
# EDGE INDEX
# =====================================================

valid_edges = df_edges[
    df_edges["txId1"].isin(node_map)
    &
    df_edges["txId2"].isin(node_map)
]

src = valid_edges["txId1"].map(node_map).values
dst = valid_edges["txId2"].map(node_map).values

edge_index = torch.tensor(
    np.vstack([src,dst]),
    dtype=torch.long
)

# =====================================================
# TIME SPLIT
# =====================================================

time_steps = df["time_step"].values

labels = df["label"].values

train_mask = (
    (labels != -1)
    &
    (time_steps <= 34)
)

val_mask = (
    (labels != -1)
    &
    (time_steps > 34)
    &
    (time_steps <= 42)
)

test_mask = (
    (labels != -1)
    &
    (time_steps > 42)
)

data = Data(
    x=x,
    edge_index=edge_index,
    y=y,
    train_mask=torch.tensor(train_mask),
    val_mask=torch.tensor(val_mask),
    test_mask=torch.tensor(test_mask)
)

print(data)

class GCN(nn.Module):

    def __init__(self,in_dim,hid_dim,out_dim):
        super().__init__()

        self.conv1 = GCNConv(
            in_dim,
            hid_dim
        )

        self.conv2 = GCNConv(
            hid_dim,
            out_dim
        )

    def forward(self,x,edge_index):

        x = self.conv1(
            x,
            edge_index
        )

        x = F.relu(x)

        x = F.dropout(
            x,
            p=0.5,
            training=self.training
        )

        x = self.conv2(
            x,
            edge_index
        )

        return x


class GraphSAGE(nn.Module):

    def __init__(self,in_dim,hid_dim,out_dim):
        super().__init__()

        self.conv1 = SAGEConv(
            in_dim,
            hid_dim
        )

        self.conv2 = SAGEConv(
            hid_dim,
            out_dim
        )

    def forward(self,x,edge_index):

        x = self.conv1(
            x,
            edge_index
        )

        x = F.relu(x)

        x = F.dropout(
            x,
            p=0.5,
            training=self.training
        )

        x = self.conv2(
            x,
            edge_index
        )

        return x


class GAT(nn.Module):

    def __init__(self,in_dim,hid_dim,out_dim):
        super().__init__()

        self.gat1 = GATConv(
            in_dim,
            hid_dim,
            heads=8
        )

        self.gat2 = GATConv(
            hid_dim*8,
            out_dim,
            heads=1
        )

    def forward(self,x,edge_index):

        x = self.gat1(
            x,
            edge_index
        )

        x = F.elu(x)

        x = F.dropout(
            x,
            p=0.5,
            training=self.training
        )

        x = self.gat2(
            x,
            edge_index
        )

        return x

def train_model(model,data):

    optimizer = torch.optim.Adam(
        model.parameters(),
        lr=0.001
    )

    train_labels = data.y[data.train_mask]

    num_licit = (train_labels == 0).sum()
    num_illicit = (train_labels == 1).sum()

    weights = torch.tensor([
      1.0,
      float(num_licit / num_illicit)
  ])

    criterion = nn.CrossEntropyLoss(
      weight=weights
  )
    for epoch in range(100):

        model.train()

        optimizer.zero_grad()

        out = model(
            data.x,
            data.edge_index
        )

        loss = criterion(
            out[data.train_mask],
            data.y[data.train_mask]
        )

        loss.backward()

        optimizer.step()

        if epoch % 10 == 0:
            print(
                f"Epoch {epoch} Loss {loss.item():.4f}"
            )

    return model

def evaluate(model,data,name):

    model.eval()

    with torch.no_grad():

        pred = model(
            data.x,
            data.edge_index
        ).argmax(dim=1)

    y_true = data.y[
        data.test_mask
    ].numpy()

    y_pred = pred[
        data.test_mask
    ].numpy()

    print("\n",name)
    print(
        classification_report(
            y_true,
            y_pred
        )
    )

    return {
        "Model":name,
        "Accuracy":accuracy_score(y_true,y_pred),
        "Precision":precision_score(y_true,y_pred),
        "Recall":recall_score(y_true,y_pred),
        "F1":f1_score(y_true,y_pred)
    }

gcn = GCN(data.num_features,64,2)
gcn = train_model(gcn,data)
gcn_result = evaluate(gcn,data,"GCN")

sage = GraphSAGE(data.num_features,64,2)
sage = train_model(sage,data)
sage_result = evaluate(sage,data,"GraphSAGE")

gat = GAT(data.num_features,8,2)
gat = train_model(gat,data)
gat_result = evaluate(gat,data,"GAT")

results = pd.DataFrame([
    gcn_result,
    sage_result,
    gat_result
])

print(results)
results.to_csv(
    "model_comparison.csv",
    index=False
)